# NumPy 


O NumPy é uma Biblioteca de Álgebra Linear para Python, o motivo pelo qual é tão importante para a Ciência de Dados com Python é que quase todas as bibliotecas do Ecossistema PyData confiam no NumPy como um de seus principais blocos de construção.

O Numpy também é rápido, pois possui ligações para as bibliotecas C. Para obter mais informações sobre por que você gostaria de usar matrizes em vez de listas, confira em [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Instruções de instalação

É altamente recomendável instalar o Python usando a distribuição Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de álgebra linear) sejam sincronizadas com o uso de uma instalação conda. Se você possui o Anaconda, instale o NumPy acessando o terminal ou prompt de comando e digitando:
    
    conda install numpy
    
**Se você não possui o Anaconda e não pode instalá-lo, consulte a documentação oficial do Numpy em várias instruções de instalação.(http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

O Numpy possui muitas funções e recursos internos. Não abordaremos todos eles, mas focaremos alguns dos aspectos mais importantes do Numpy: vetores, matrizes, matrizes e geração de números. Vamos começar discutindo matrizes.

# Numpy Arrays

As matrizes NumPy são a principal maneira de usarmos o Numpy ao longo do curso. Matrizes numpy vêm basicamente em dois sabores: vetores e matrizes. Os vetores são estritamente matrizes 1-d e matrizes são 2-d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes NumPy.

## Criando matrizes NumPy

### De uma lista Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos internos

Existem várias maneiras internas de gerar matrizes


### arange

Retorne valores espaçados uniformemente dentro de um determinado intervalo.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])


### zeros e uns

Gere matrizes de zeros ou uns

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Retornar números espaçados uniformemente em um intervalo especificado.

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye


Cria uma matriz de identidade

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

O Numpy também tem várias maneiras de criar matrizes de números aleatórios:

### rand
Crie uma matriz da forma especificada e preencha-a com
amostras aleatórias de uma distribuição uniforme
sobre `` [0, 1) ``.

In [13]:
np.random.rand(2)

array([0.32638355, 0.05473877])

In [14]:
np.random.rand(5,5)

array([[0.78740931, 0.53182443, 0.32493586, 0.35991399, 0.08686724],
       [0.39240353, 0.49701177, 0.87196721, 0.43807383, 0.93231502],
       [0.8824086 , 0.77012811, 0.55268433, 0.45177738, 0.29262331],
       [0.891028  , 0.55036469, 0.62193958, 0.19946762, 0.11859451],
       [0.2971507 , 0.42488668, 0.35118914, 0.44673228, 0.87328524]])

### randn


Retorne uma amostra (ou amostras) da distribuição "normal normal". Ao contrário do rand, que é uniforme:

In [15]:
np.random.randn(2)

array([ 0.95558883, -1.1673008 ])

In [16]:
np.random.randn(5,5)

array([[ 7.53774438e-01,  4.01808300e-01,  8.46877960e-01,
         2.69358991e-04, -2.04828637e-01],
       [ 8.94347368e-01,  1.00867895e+00, -8.62655738e-01,
         2.11098708e-01,  1.16092705e-01],
       [ 1.12471320e+00,  1.24665317e+00,  8.52222990e-02,
         1.20248754e+00,  3.64144021e-01],
       [-9.45349917e-01, -2.78573060e+00,  2.07926489e-02,
        -6.19322858e-01,  3.80505309e-01],
       [-8.48853759e-01,  1.53778467e+00,  1.68984879e+00,
        -9.57734587e-01, -9.12302800e-01]])

### randint
Retorne números inteiros aleatórios de `baixo` (inclusive) para` alto` (exclusivo).

In [17]:
np.random.randint(1,100)

24

In [18]:
np.random.randint(1,100,10)

array([87, 27, 28,  7, 77,  7, 69, 96, 18, 55])


## Atributos e métodos de matriz

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [19]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr

array([21, 40, 14, 29, 29,  0, 16, 18, 16, 25])

## Reshape
Retorna uma matriz que contém os mesmos dados com uma nova forma.

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos. Ou para encontrar seus locais de índice usando argmin ou argmax

In [23]:
ranarr

array([21, 40, 14, 29, 29,  0, 16, 18, 16, 25])

In [24]:
ranarr.max()

40

In [25]:
ranarr.argmax()

1

In [26]:
ranarr.min()

0

In [27]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [28]:
# Vector
arr.shape

(25,)

In [29]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [30]:
arr.reshape(1,25).shape

(1, 25)

In [31]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.reshape(25,1).shape

(25, 1)

### dtype


Você também pode pegar o tipo de dados do objeto na matriz:

In [33]:
arr.dtype

dtype('int64')


# Bom trabalho!