# Gradiente Descendente

O gradiente descendente é um algoritmo de otimização que usa as derivadas da função objetivo
para encontrar o ponto com maior inclinação. No processo, as variáveis a otimizar são deslocadas
em uma direção negativa o qual reduzirá o valor da função objetivo.

Algoritmo geral para atualizar os pesos com gradiente descendente:
<p>
<img src='RNA-Gradiente.png' /><br>
</p>

## Vamos implementar o algoritmo do Gradiente Descendente!
#### Importando a biblioteca

In [12]:
import numpy as np

#### Função do cáculo da sigmóide

In [13]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

#### Derivada da função sigmóide

In [14]:
#termo de erro
def sigmoid_prime(x):
        return sigmoid(x) * (1 - sigmoid(x))

#### Vetor dos valores de entrada e saídas

In [15]:
x = np.array([1, 2, 3, 4])
y = np.array(0.5)
b = 0.5

#### Pesos iniciais das ligações sinápticas 
Nota: Inicializados aleatóriamente

In [16]:
# Pesos iniciais
w = np.array([0.5, -0.5, 0.3, 0.1])

#### Taxa de Aprendizagem

In [17]:
learnrate = 0.5

### Calcule um degrau de descida gradiente para cada peso

In [18]:
# TODO: Calcule a combinação linear de entradas e pesos sinápticos
h = np.dot(x,w) + b

# TODO: Calcule a saída da Rede Neural
nn_output = sigmoid(h)

# TODO: Calcule o erro da Rede Neural
error = y - nn_output

# TODO: Calcule o termo de erro
error_term = error * sigmoid_prime(h)

# TODO: Calcule a variação do peso
del_w = learnrate * error_term * x


In [19]:
print('Saída da Rede Neural:')
print(nn_output)
print('\n\nErro:')
print(error)
print('\n\nVariação dos pesos:')
print(del_w)

Saída da Rede Neural:
0.7858349830425586


Erro:
-0.2858349830425586


Variação dos pesos:
[-0.02405278 -0.04810556 -0.07215834 -0.09621112]


---

In [20]:
w = w + del_w

h = np.dot(x,w)+b

nn_output = sigmoid(h)

error = y - nn_output

error_term = error * sigmoid_prime(h)

del_w = learnrate * error_term * x

print('Saída da Rede Neural:')
print(nn_output)
print('\n\nErro:')
print(error)
print('\n\nVariação dos pesos:')
print(del_w)

Saída da Rede Neural:
0.6407029861341647


Erro:
-0.14070298613416465


Variação dos pesos:
[-0.0161951  -0.0323902  -0.0485853  -0.06478041]


---

In [21]:
w = w + del_w

h = np.dot(x,w)+b

nn_output = sigmoid(h)

error = y - nn_output

error_term = error * sigmoid_prime(h)

del_w = learnrate * error_term * x

print('Saída da Rede Neural:')
print(nn_output)
print('\n\nErro:')
print(error)
print('\n\nVariação dos pesos:')
print(del_w)

Saída da Rede Neural:
0.5231243816830907


Erro:
-0.023124381683090722


Variação dos pesos:
[-0.00288436 -0.00576873 -0.00865309 -0.01153746]
